ALTER TABLE `students` ADD `sexo` text;--> statement-breakpoint
ALTER TABLE `students` ADD `turma` text;--> statement-breakpoint
ALTER TABLE `students` ADD `matricula` text;--> statement-breakpoint
ALTER TABLE `students` ADD `prof_regular` text;--> statement-breakpoint
ALTER TABLE `students` ADD `coordenadora` text;--> statement-breakpoint
ALTER TABLE `students` ADD `diagnostico_cid` text;--> statement-breakpoint
ALTER TABLE `students` ADD `classificacao` text;--> statement-breakpoint
ALTER TABLE `students` ADD `medicamentos` text;--> statement-breakpoint
ALTER TABLE `students` ADD `alergias` text;--> statement-breakpoint
ALTER TABLE `students` ADD `terapias_atuais` text;--> statement-breakpoint
ALTER TABLE `students` ADD `historico_medico` text;--> statement-breakpoint
ALTER TABLE `students` ADD `mae_nome` text;--> statement-breakpoint
ALTER TABLE `students` ADD `mae_idade` text;--> statement-breakpoint
ALTER TABLE `students` ADD `mae_profissao` text;--> statement-breakpoint
ALTER TABLE `students` ADD `mae_escolaridade` text;--> statement-breakpoint
ALTER TABLE `students` ADD `pai_nome` text;--> statement-breakpoint
ALTER TABLE `students` ADD `pai_idade` text;--> statement-breakpoint
ALTER TABLE `students` ADD `pai_profissao` text;--> statement-breakpoint
ALTER TABLE `students` ADD `pai_escolaridade` text;--> statement-breakpoint
ALTER TABLE `students` ADD `composicao_familiar` text;--> statement-breakpoint
ALTER TABLE `students` ADD `endereco` text;--> statement-breakpoint
ALTER TABLE `students` ADD `rotina_familiar` text;--> statement-breakpoint
ALTER TABLE `students` ADD `comunicacao_casa` text;--> statement-breakpoint
ALTER TABLE `students` ADD `desenv_motor` text;--> statement-breakpoint
ALTER TABLE `students` ADD `desenv_linguagem` text;--> statement-breakpoint
ALTER TABLE `students` ADD `desenv_cognitivo` text;--> statement-breakpoint
ALTER TABLE `students` ADD `desenv_social` text;--> statement-breakpoint
ALTER TABLE `students` ADD `desenv_autonomia` text;--> statement-breakpoint
ALTER TABLE `students` ADD `comportamento_emocional` text;--> statement-breakpoint
ALTER TABLE `students` ADD `hab_leitura` text;--> statement-breakpoint
ALTER TABLE `students` ADD `hab_escrita` text;--> statement-breakpoint
ALTER TABLE `students` ADD `hab_matematica` text;--> statement-breakpoint
ALTER TABLE `students` ADD `tipo_atendimento` text;--> statement-breakpoint
ALTER TABLE `students` ADD `frequencia` text;--> statement-breakpoint
ALTER TABLE `students` ADD `dificuldades_iniciais` text;--> statement-breakpoint
ALTER TABLE `students` ADD `potencialidades` text;--> statement-breakpoint
ALTER TABLE `students` ADD `barreiras` text;--> statement-breakpoint
ALTER TABLE `students` ADD `necessidades_acessibilidade` text;--> statement-breakpoint
ALTER TABLE `students` ADD `expectativas_familia` text;